User Reservation: Add Map View & Update Address Form
pokemon-parKing/parKing-client pull request #4
Opened 2023-12-27 19:24 UTC by clee4037

- Integrated map view
- Connected front and backend
- Using geocode endpoint to convert address to long and lat coordinates
- Removed country field from address from
- Added 2 letter state dropdown to address form
- Added route to user reservation page

2023-12-27 19:45 UTC, stevkim commented on src/App.jsx
XD the pokemon path lol

2023-12-27 19:47 UTC, stevkim commented on src/components/user-reservation/MapView.jsx
Super cool how you got the maps going

2023-12-27 19:49 UTC, stevkim approved these changes
Everything looks good to me!
Quick note - it looks like getGarageData/getGeoCoordinates are the same functions?
Also, idk if its a Supabase thing but you might not need to JSON.parse the data? *would need to test this

2023-12-27 20:19 UTC, clee4037 commented
@stevkim 
Good catch -- getGarageData is WIP!
I tested and JSON.parse is required.

2023-12-28 05:24 UTC, bzw24 requested changes
Made note on one change for compilation issues. Otherwise module is looking good. I like the separations of concerns by separating axios calls under the utils folder.

Under your UserReservation.jsx, edit the path to: "../components/user-reservation/Confirmation.jsx" to eliminate compilation error (your component is named 'Confirmation.jsx' not 'confirmatin.jsx' (capitalization)

2023-12-28 05:24 UTC, bzw24 commented on src/containers/UserReservation.jsx
Edit to: "../components/user-reservation/Confirmation.jsx" to eliminate compilation error (your component is named 'Confirmation.jsx'

2023-12-28 05:45 UTC, bzw24 approved these changes

2023-12-28 05:45 UTC, merged